name: qwiva_waitlist
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # For SVG image
  flutter_svg: ^0.22.0

  sizer: ^2.0.15

  # For spacing
  gap: ^2.0.0

  # Native splash
  flutter_native_splash:

  cloud_firestore: ^4.2.0


dev_dependencies:

flutter_native_splash:
  color: "#0B1E4B"
  web: true
  image: assets/images/icon.png

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.otf
    - family: Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.otf
    - family: Semibold
      fonts:
        - asset: assets/fonts/Gilroy-Semibold.otf
    - family: Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.otf

  assets:
    - assets/svg/
    - assets/fonts/
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
