// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCflsZnyywCyrdFJhGoFbpab60hKwgFHFQ',
    appId: '1:621586262976:web:46deac21a74e9f103eb625',
    messagingSenderId: '621586262976',
    projectId: 'gleaming-baton-369011',
    authDomain: 'gleaming-baton-369011.firebaseapp.com',
    storageBucket: 'gleaming-baton-369011.appspot.com',
    measurementId: 'G-XX85GB9R6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL4OMd6BhbN3jGtcphxcH03W241N7MQTg',
    appId: '1:621586262976:android:6ac433827eca70c53eb625',
    messagingSenderId: '621586262976',
    projectId: 'gleaming-baton-369011',
    storageBucket: 'gleaming-baton-369011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvFhQcjIG9-b-kzgF0OBxJbka-GfwXNyk',
    appId: '1:621586262976:ios:e9b1453175cf4dd03eb625',
    messagingSenderId: '621586262976',
    projectId: 'gleaming-baton-369011',
    storageBucket: 'gleaming-baton-369011.appspot.com',
    androidClientId: '621586262976-9fludf3rujvldcasp5frvcimaqglum0n.apps.googleusercontent.com',
    iosClientId: '621586262976-q78ll6ca0ht9epqrplde3p5fq8uljgop.apps.googleusercontent.com',
    iosBundleId: 'web.qwiva.io.qwivaWaitlist',
  );
}
